### ISSUE TITLE
limit to zoom to horizontal (x) or vertical (y)

### ISSUE THREAD

**Issue by timelyportfolio** [ariutta/svg-pan-zoom#124]
Based on #37, I see how to easily limit the panning to one axis.  However, zooming does not offer this functionality.  Would it be possible to limit the zoom easily to one axis?  Although this is not the expected application, but maybe something like a timeline where we would like to zoom to a particular subperiod.

Related to https://github.com/timelyportfolio/svgPanZoom/issues/8

**Comment by bumbu** [comment]
I believe that it is possible to be done now. There are 2 different features that should allow that:
* you can return `false` from `beforeZoom` and that zooming will get canceled
* you can dynamically update min/maxZoom via `setMaxZoom` and `setMinZoom`

Can you please explain in more detail how limiting zooming on one axis should work? It is just hard for me to understand how you can limit zoom on one axis because zooming is done for both axis in parallel.

**Comment by bumbu** [comment]
I'm closing this issue until more details are provided.
