### ISSUE TITLE
TypeError: Value being assigned to SVGMatrix.a is not a finite floating-point value

### ISSUE THREAD

**Issue by jeremyVignelles** [ariutta/svg-pan-zoom#130]
I've seen other bugs of the same kind but not in the same case, so here's mine:

Code used :
http://jsfiddle.net/0r68rdb5/1/

On firefox, I get : 
`TypeError: Value being assigned to SVGMatrix.a is not a finite floating-point value.`

Chrome behaves strangely as well.

It seems that it is due to the viewbox I have defined. I will try to do without in the meantime.

**Comment by ariutta** [comment]
Great bug report -- thanks!

You're right -- there's something going on with the viewbox, because the error doesn't happen if I delete the viewbox. I tried changing the `-10` values to positive values and also tried setting specific pixel values for SVG width/height, but that didn't make any difference:
http://jsfiddle.net/0r68rdb5/2/

I know we had issues with this for IE9 in the past but thought it was working for other browsers. Could you check [previous releases](https://github.com/ariutta/svg-pan-zoom/releases) to see whether this is a regression error?

**Comment by jeremyVignelles** [comment]
Tried with several versions. some versions didn't work, maybe did I make some mistakes in initialization or maybe it was bugs that were fixed in later versions.
Here is a try with v2.3.10, that has the same issue :
http://jsfiddle.net/0r68rdb5/6/

**Comment by ariutta** [comment]
Checked the console for http://jsfiddle.net/0r68rdb5/6/ and noticed this:

Refused to execute script from 'https://raw.githubusercontent.com/ariutta/svg-pan-zoom/2.3.10/dist/svg-pan-zoom.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

I updated the URL for v2.3.10, and it works:
http://jsfiddle.net/0r68rdb5/12/

It still does give the following errors, but they don't prevent pan/zoom from working (tested in Chrome):
```
Error: Invalid value for <g> attribute transform="matrix(NaN,0,0,NaN,NaN,NaN)"
Error: Invalid value for <g> attribute transform="matrix(1,0,0,1,NaN,NaN)"
```

I also tried v2.3.11 and got the same result as for v2.3.10:
http://jsfiddle.net/0r68rdb5/13/

I'd suggest checking the differences between the versions. Also @bumbu may know of a quick fix.

**Comment by jeremyVignelles** [comment]
I'm afraid the http://jsfiddle.net/0r68rdb5/12/ doesn't work in FF (same error). Chrome has a strange behaviour, since I expect the circle to fit the SVG.

**Comment by bumbu** [comment]
The problem was that we were parsing the `viewBox` attribute by assuming that values can be split by spaces only, but from official documentation
> the `viewBox` attribute is a list of four numbers `<min-x>`, `<min-y>`, `<width>` and `<height>`, separated by whitespace and/or a comma

I added support for parsing viewBox taking in account this rule.

Thanks for bug report!

**Comment by jeremyVignelles** [comment]
Indeed!, when using spaces in my viewbox attribute, it now works: http://jsfiddle.net/0r68rdb5/14/

Thanks for your help :smiley:

**Comment by bumbu** [comment]
I pushed changes to `gh-pages` branch so now your old example is also working (you only have to update your browser cache)
