### ISSUE TITLE
Set purely zoom level

### ISSUE THREAD

**Issue by ninjaprox** [ariutta/svg-pan-zoom#167]
I'm using one another library along with svg-pan-zoom to create panning and zooming animation simultaneously. After the animation finished by that library, svg-pan-zoom doesn't have actual zoom level. How can I purely set zoom level value in svg-pan-zoom without zooming anymore? Or is there other ways to work around this?

**Comment by bumbu** [comment]
You can't directly change internal cached values. But what you can do is trick the library:
* Get the ratio between actual zoom (via `getSizes()`) and svgPanZoom virtual zoom (via `getZoom()`)
* After another library finishes animation, compute what pan and zoom values should be for svgPanZoom
* zoom and pan through svgPanZoom with values you computed previously
If you did all right then the svgPanZoom will zoom and pan the SVG, but because these values are the save to current SVG state - visually there will be no changes. And svgPanZoom will update its cache.
