### ISSUE TITLE
Problem with zoomAtPoint

### ISSUE THREAD

**Issue by bslade** [ariutta/svg-pan-zoom#183]
I've attached an test example of zoomAtPoint that's not working for me.   I'm not a regular JavaScript/SVG user so I'm learning how to do things.   I'm probably doing something wrong with viewbox coordinates, but I don't know what that is.

Note that, in the example, the "2nd Sample text" element's y coordinate is outside the svg box.

[test_zoomAtPoint.zip](https://github.com/ariutta/svg-pan-zoom/files/74922/test_zoomAtPoint.zip)

All help or feedback appreciated.
Ben Slade
Kensington MD

**Comment by bumbu** [comment]
Can you please upload your example [somewhere online](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues)? You can start with [this example](http://jsfiddle.net/bumbu/167usffr/) and edit it.

**Comment by bumbu** [comment]
Also you may be better asking this on [stackoverflow](https://github.com/ariutta/svg-pan-zoom#questions-how-tos-need-help) as these tracker is used for development and bugs topics.

**Comment by bslade** [comment]
Re: Can you please upload your example somewhere online? You can start with this example and edit it.

Done.  Take a look at http://jsfiddle.net/167usffr/196 . As I understand it, clicking on the "Zoom" button should zoom to point 10,10 which should be the upper left corner of the svg rectangle/square .   But it doesn't do that.

Re: better asking this on stackoverflow

Well, it sure seems like it's not working properly, which is why I'm here.   But next time I'll go to stackoverflow first.

**Comment by bumbu** [comment]
When you do zoom at point - it zooms to a rendered (visible) point. 
In your case if you try to zoom at point `10,10` then it will zoom into top-left corner (which is empty). 
If you want to zoom into the middle of visible point then you [have to zoom into point `150,150`](http://jsfiddle.net/167usffr/197/) as your SVG has width and height of 300.

If you want to zoom at point `10,10` of SVG content you can do:
### The simple way
[zoom to level 1, center and zoom to a specific point](http://jsfiddle.net/167usffr/198/). This will work because `zoom(1)` and `center` will make you content to take all available space. 
![image](https://cloud.githubusercontent.com/assets/171178/12062824/2bd3b046-af9b-11e5-9c30-963c18dc3866.png)

Then zooming at any point will zoom into the content.
![image](https://cloud.githubusercontent.com/assets/171178/12062828/3880f1aa-af9b-11e5-8e9a-88ef96ab5bda.png)

```    
panZoomInstance.zoom(1)
panZoomInstance.center()
panZoomInstance.zoomAtPoint(2,{x: 10, y: 10});
```

This method should be fine as users in most cases will not see the flickering because render is deferred.

### More complicated way
It is possible to calculate where exactly point `10,10` or a rendered element lies on the screen. For this you have to use `panZoomInstance.getSizes()` method that will tell you:
* SVG sizes
* SVG content sizes and pan
* Actual zoom
Using all these you can compute where your desired point is rendered and zoom into that point.
