### ISSUE TITLE
Uncaught TypeError: Cannot read property 'documentElement' of null

### ISSUE THREAD

**Issue by gfoiani** [ariutta/svg-pan-zoom#187]
Hi,

I'm trying to integrate this library inside my React project. 
I'm using 3.2.6 version of the library on Chrome Browser.
I tried to reproduce the tiger example, this is my code:

```
import React, { Component } from 'react';
import SvgPanZoom from 'svg-pan-zoom';

export default class Map extends Component {

  componentDidMount() {
    SvgPanZoom('#demo-tiger',{
      zoomEnabled: true,
      controlIconsEnabled: true,
      fit: true,
      center: true,
    });
  }

  render() {
    const style = {
      width: '1000px',
      height: '700px'
    };
    return (
      <div>
        <embed id="demo-tiger" type="image/svg+xml" style={style} src={require('../images/tiger.svg')} />
      </div>
    );
  }
}
```

The svg file is correctly rendered but I cannot zoom or pan and I get the following error in the console.

`Uncaught TypeError: Cannot read property 'documentElement' of null` at line 90 of the utilities.js file.

http://jsfiddle.net/gfoiani/8jzdc2tm/

**Comment by bumbu** [comment]
This seems to be a problem of timing. 
`componentDidMount` is called right after the render, and it's called on children first. That means (imho, didn't test) that the embed it not yet injected into DOM. That's why the element it not found. 

As per [react documentation](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount) you can
> At this point in the lifecycle, you can access any refs to your children

So you should pass [a reference to the actual embed element](https://facebook.github.io/react/docs/more-about-refs.html) instead of it's ID. 

Alternatively you can init svg-pan-zoom when component is injected into DOM (if it is possible to know when this event occurs).
