### ISSUE TITLE
mouse over problems because of changing order in how svg elements displays

### ISSUE THREAD

**Issue by myrmecia** [ariutta/svg-pan-zoom#192]
Hello, i have different layers :
-the first is a card;
-the second is a bigger card that appear when the user mouse over the third layer;
-the third is exactly the same structure than the first but is used only to trigger the mouse over;

working example :
[](http://arbre.mifaloca.com/git/index.php)

the problem is that the script seems to rewrite some elements and modify the struture of layers, what gives a glitching appear/disappearing "big card" effect due to the fact that the triggering layer has passed beneath the "big card" layer.

**Comment by bumbu** [comment]
That's true that svg-pan-zoom creates a group element if it doesn't find the one it needs. You can read more about it [here](https://github.com/ariutta/svg-pan-zoom#using-a-custom-viewport). 

Please provide a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues), otherwise it's almost impossible to help.
