### ISSUE TITLE
why not support img element

### ISSUE THREAD

**Issue by sivasaravanand** [ariutta/svg-pan-zoom#196]
Hi
I am trying to implement this plugin into svgeditor(https://github.com/SVG-Edit/svgedit) to make smooth zoom but when i load image inside the svg it got failed. so may i know why it is not supporting

Thanks,
Shiva

**Comment by ariutta** [comment]
Browsers disable scripts for image elements.

**Comment by sivasaravanand** [comment]
Thank you. It helped me a lot

**Comment by ariutta** [comment]
I assume you meant you have an HTML img element with the src referencing an
SVG.

But if you have an inline SVG that contains an image element with a PNG,
that should work OK. If it doesn't, let us know, because that's a bug.
On Apr 17, 2016 8:11 PM, "sivasaravanand" <notifications@github.com> wrote:

Thank you. It helped me a lot

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/ariutta/svg-pan-zoom/issues/196#issuecomment-211169442>

**Comment by sivasaravanand** [comment]
I misunderstood when i read an examples, now it works perfectly ( i have img element but it is inside svg)
