### ISSUE TITLE
zoom to extent

### ISSUE THREAD

**Issue by dshorthouse** [ariutta/svg-pan-zoom#232]
I've been trying to implement an unnecessarily complex combination of zoom and pan but I now realize that what I was doing was describing an extent. A very useful new method for me would be zoomAtPoints (note the plural). Given an array of points, the viewport would be panned and zoomed to the bounding box of those points.

**Comment by bumbu** [comment]
Hi @dshorthouse, 

Thanks for the idea!. This looks like an useful feature, but it is very specific and is outside of the main purpose of the library. That functionality can be implemented as a standalone extension to the library (e.g. thumbnailViewer). If you're going to implement that and make a pull request, I'll be happy to merge it into demo folder (as we don't have any proper way of defining plugins). 

But I'm going to close this issue based on what I wrote above and because it is not an issue.
