### ISSUE TITLE
Don't trigger onPan if pan value is the same after beforePan transformations

### ISSUE THREAD

**Issue by smargovsky** [ariutta/svg-pan-zoom#241]
Bug report
---

### Expected behaviour
Allow synchronized zoom / pan with panning limited to only horizontal.

### Actual behaviour
Zooming causes a RangeError: Maximum call stack size exceeded

### Steps to reproduce the behaviour

1.  In sinchronized.html demo, add `beforePan` to limit to only horizontal panning
       ```
       window.zoomTiger = svgPanZoom('#demo-tiger', {
          zoomEnabled: true,
          controlIconsEnabled: true,
          beforePan: function(oldP, newP) { return {x:true, y:false}; }
        });
        window.zoomTiger2 = svgPanZoom('#demo-tiger2', {
          zoomEnabled: true,
          controlIconsEnabled: true,
          beforePan: function(oldP, newP) { return {x:true, y:false}; }
        });
      ```
2.  Run demos and attempt to pan / zoom.

### Configuration

- svg-pan-zoom version: `3.5.0`
- Browser(s): `Chrome / Safari / All others suspected too`
- Operating system(s): `Mac`

**Comment by bumbu** [comment]
Hi @smargovsky 

#### Short story
Add beforePan only to one SVG, it will keep both of them in sync:
```js
window.zoomTiger = svgPanZoom('#demo-tiger', {
   zoomEnabled: true,
   controlIconsEnabled: true,
   beforePan: function(oldP, newP) { return {x:true, y:false}; }
 });
 window.zoomTiger2 = svgPanZoom('#demo-tiger2', {
   zoomEnabled: true,
   controlIconsEnabled: true
 });
```

#### Long story
It is and it's not at the same time the library's fault. 
This happens because `onPan` gets triggered even if `beforePan` made old and new pan values the same. So in this case first and second instances get into an infinite loop of trying to pan each others' pan value, and since that doesn't change for nor of them - they get stuck in that loop. 

I'm going to fix that behaviour, but it's still not what you want as if you'll cancel both SVGs' Y pan, whey will still end up having different Y values if you're going to zoom using mouse or touch gestures. That's because when you zoom with a mouse, the SVG gets zoomed relative to the mouse location, but in the code we do `zoomTiger2.pan(point)` which zooms relative to the centre of the SVG.  So the best solution if to have just one `beforePan` as the second one will get synchronised based on that.
