### ISSUE TITLE
Persisting SVG pan and zoom values between page refreshes

### ISSUE THREAD

**Issue by danielspaniel** [ariutta/svg-pan-zoom#255]
Hi there, 
 I have been enjoying the pan zoom action, and found myself wanting to save the matrix setting and then using it again on the page reload. So I thought to myself, why don't I just add that to the options that you allow in svg-pan-zoom? 
 Are you open to that?

**Comment by ariutta** [comment]
Hi! @bumbu is leading development on this now, so I'll defer to him. But speaking generally, the setting you are describing might be useful for multiple purposes, such as using this library as a React component and working with lifecycle events. What do you think @bumbu?

**Comment by bumbu** [comment]
Hi @danielspaniel,

Sorry for a late reply, I was on holidays. 

It sounds like an useful feature but I'm not sure I fully understand it. Do you mean saving matrix settings (say in cookies or localstorage) and then when reloading the plugin (on page reload or on plugin destruction and then initialisation) it would load those settings and apply them? Or in simpler words you want to be able to zoom/pan to a specific point in SVG, and after page reload the SVG would be automagically zoomed/panned to that position. Is that right?

If above assumptions are correct then there are few things to take into account:
* Providing only a boolean config option is not going to be enough because:
    * Some users may want to store those settings in cookies, or localstorage, or sessionstorage, or URL hash, or server...
    * Some users may want to store only pan or only zoom, or store those settings only in certain circumstances
* Storing data would require some way to uniquely identify different SVGs (so that each different SVG will have its own settings)
* What if the same SVG is loaded multiple times (multiple instances) on the same page?
* We would probably want to store pan and zoom values and not matrix transform values as these 2 things are separated in code, and we don't really use matrix transform values, pan and zoom values serve as the source of truth. So if we would simply apply the matrix transform values, they would get overwritten by internal pan and zoom values. 
* In between page reloads, SVG container size (width, height) may change, and what was in centre of viewport when settings were saved, may not be in centre anymore if SVG container size is different on following plugin initialisation. 

There should be more edge-cases and things to think about. But I hope it gives us a rough idea of how complex this _little_ feature is. 

Instead I'd go with something simpler: using the API and handling only those issues that are relevant in case-by-case basis. For example if I'd want that functionality for a single SVG on my page, I'd fine with storing data in cookies and I would know that SVG container size is the same - I'd write something like:

```js
$(function() {
  panZoomInstance = svgPanZoom('#svg-id', {
    onZoom: function() {saveSettings(panZoomInstance)},
    onPan: function() {saveSettings(panZoomInstance)}
  });
  
  var settings = loadSettings();
  if (settings) {
    panZoomInstance.zoom(settings.zoom);
    panZoomInstance.pan(settings.pan);  
  }
})
```

I created a [JSFiddle example](http://jsfiddle.net/bumbu/167usffr/799/). 

Doing so is of course more troublesome than having a boolean option, but that's only until someone will want more customisation freedom. That's why I'd just go for now with having a demo in our docs on how that can be achieved and not introducing more complexity to the codebase. 

Let me know what do you think about that.

**Comment by danielspaniel** [comment]
Holey cow @bumbu, now that was a ridiculously simple solution to what I thought was a ridiculously simple pull request. As you point out, I reckon it's not so simple.  👍 

Originally I was trying to save the matrix as a viewBox ( could not figure out how to convert the matrix back to viewBox values ) .. then I was going to slap that viewBox setting on the svg that I wanted the saved size. Then svg-pan-zoom would load up and when it initialized would grab that viewBox setting and initialize with that. 

So I was working on a method called toViewBox but I could not figure it out. 

 That (toViewBox ) is probably the ideal solution for me because there would be no jitter ( as the svg renders and then rerenders when you set the pan/zoom after initialization ) 

But being that your idea adds zero to the code base and it works right now .. sign me up for that one. 
 Thanks for making that fiddle. Shows it working load and clear. 

 If ever feel mathematically deprived and you ever want talk about converting matrix to viewBox values .. I would love to try and work that out .. mostly just for the fun ( and because it irks me that I could not get it ( got about 80% there )

**Comment by bumbu** [comment]
Working with matrix transform, viewbox and correct zooming was always challenging for me, so I feel your frustration!

As for jitter - having a `toViewBox` method may not help with that. Probably nothing in the library will solve that problem 100% of time. That's because no matter what, but if you initialise *svg-pan-zoom* when DOM is ready, then most probably the browser managed to render the SVG in its pristine representation. And then when *svg-pan-zoom* kicks in - you'll see the jitter. 

A better solution to prevent jitter would be to set opacity 0 to the SVG (from CSS or directly in HTML). After plugin is initialised - remove the opacity property.
Alternatively it is possible to inject SVG into the DOM after the DOM ready callback, and then immediately initialise *svg-pan-zoom*. But this approach may have jitter from time to time.

**Comment by danielspaniel** [comment]
hmm .. pretty good point there!

**Comment by danielspaniel** [comment]
@bumbu, can you do me a huge favour and try your jsfiddle example ( above ) with the latest svg-pan-zoom code ( 3.5.1 ). Your demo of how to save pan/zoom worked so well, I was baffled for days as to why it did not work for me. 
Then I checked your version in the jsfiddle and it is => 3.2.5, whereas in my application I was using 3.5.1, and it was not working correctly.  In the new version when you set the zoom / pan it does not set the pan zoom with what you tell it to, it alters them a bit because the initial matrix setup is different. 
 I reverted to 3.2.5 to make it work, and I don't mind that I spent many many hours wondering what the heck was going on that it would not work for me, it just might be nice to know that it works in current versions too.

**Comment by bumbu** [comment]
Hi @danielspaniel ,

I'm really sorry to hear that you lost lots of time with that. 
I pushed latest version into `gh-pages` branch (the one used by jsfiddle) and tried my previous example - and it seems to work. Actually first time it didn't work, and I started debugging, but then it suddenly started working. So now I'm not sure if that was my mistake, or if there is indeed a bug. 

I was using [this page](http://fiddle.jshell.net/bumbu/167usffr/799/show/light/) which is just the _result_ view of jsfiddle to get easier access to cookies. I tried running it in chrome, incognito chrome and firefox (which works only with [that](http://fiddle.jshell.net/bumbu/167usffr/799/show/) link - and in all cases it works perfectly. 

If you can provide a reproducible example - we can try and debug it. If it's a library issue - then it's definitely worth fixing...

**Comment by danielspaniel** [comment]
The reason it works "perfectly" is because you have your svg canvas setup as a perfect square. If you make it a rectangle, it will no longer work so perfectly. 
 If you can get a jsfiddle up with the v3.5.2 ( latest )  code up there I can show you what I mean.

**Comment by danielspaniel** [comment]
I am going to close this because, yes, you were right that it does work on the newest versions.  For the simple case we have in the fiddle it is perfect. 

The only thing that makes me sad, is that I still am not getting the pan zoom settings to refresh perfectly in certain situations as I would if I could save the actual viewbox settings.  But until I get a way to reproduce it for you I am outta luck.
