### ISSUE TITLE
svg coordinate when window resize

### ISSUE THREAD

**Issue by msh666** [ariutta/svg-pan-zoom#272]
Hi there, 

I faced with the problem and do not find the solution there

I have a container with svg image. I can zomm and drag it. 
So, full screen browser window I zoom to some place on svg,
 then I resize my browser and made svg .fit() in container.

So the problem. How to calculate pan coordinate to move and zoom to the same part of svg as in fullscreen?

**Comment by bumbu** [comment]
First take a look at [window resize demo](http://ariutta.github.io/svg-pan-zoom/demo/resize.html). You have to call `.resize()` method on your instance of svgPanZoom after page resizes so that your plugin would work correctly.

> How to calculate pan coordinate to move and zoom to the same part of SVG as in fullscreen?

It depends what do you mean "to the same part of SVG". Is it the centre of the visible area, or maybe the centre of the figure that was in visible area? I'd suppose you mean the centre of the visible area. In that case you'll have to:
* On each zoom and pan event calculate the centre of the visible area by using the values provided by the  `.getSizes()` method, zoom from `.getZoom()` and pan from `.getPan()`. You'll have to come with that formula by yourself. 
* Whenever window resizes, you have to calculate again what's the new visible centre, where this centre should be (based on calculations before the resize). Then by using this 2 points, pan from first point to the second one. 

Sorry that I can't provide any code examples or an MVP, but that's for your to try. But if you do come with a solution - feel free to share it here. It will be useful for other people who may want the same functionality.

**Comment by msh666** [comment]
Hi there. Thank you for the answer.

I find solutions, some thing like this (code attached):

```javascript
            var currentZoom = _panZoom.getZoom();
            var s = _panZoom.getSizes();
            var p = _panZoom.getPan();
	    var relativeX = s.width / 2 / (p.x + s.viewBox.width * s.realZoom);
            var relativeY = s.height / 2 / (p.y + s.viewBox.height * s.realZoom);
       
	    _panZoom.resize();
	    _panZoom.fit();

            _panZoom.zoomBy(currentZoom);
            s = _panZoom.getSizes();
            var x = (s.width / 2 / relativeX) - s.viewBox.width * s.realZoom;
            var y = (s.height / 2 / relativeY) - s.viewBox.height * s.realZoom;
            _panZoom.pan({ x: x, y: y });

            _endZoomOrPan();
```
It works perfect as I need, bt there are some problem. May be it is a bug of library or my mistake.
Let me try to explain what I mean. 
Everything cool. I can zoom, move svg and when I resize window all fit as I want, but
it is going wrong when i refresh the page.

Example:
1) Full screen browser
2) Zoom and move to some place on svg
3) Made window smaller
4) svg resize, fit, zoom and move to the **right** place.
5) Refresh page
6) svg resize, fit, zood and move to the **wrong** place.

Why I think this happend, According to the soltion I represent. When we refresh the page then
take Sizes() and Pan() it's return sizes for **small** window. but pan (as I understood it's coordinates) for **fullscreen** window instead of small. 

So when we just resize broweser from fullscreen to small 
```
            var s = _panZoom.getSizes();
            var p = _panZoom.getPan();
```
here we have fullscreen sizes and coordinates and after .resize() 
`            s = _panZoom.getSizes();`
here sizes become for small window and everything working cool

but with refreshing both time sizes come for smaller window and Pan for big. 

Hope I explain it correctly and you can understand me.

**Comment by bumbu** [comment]
Hi @msh666 ,

Really glad to hear that you found a solution.
Related to the browser resize - it's really hard to understand what's happening without actually seeing it. If you would post a reproducible example (e.g. [jsfiddle](http://jsfiddle.net/bumbu/167usffr/)) that could help to understand better the issue.

**Comment by bumbu** [comment]
Closing as no further comments provided
