### ISSUE TITLE
Disable Click in pan zoon event

### ISSUE THREAD

**Issue by snowsem** [ariutta/svg-pan-zoom#282]
How to disable click when moving svg?

example:

$(document).on("click", "polygon", function() {
  console.log('click');
});
when i panning, in console show click.

another plug-in has an event:

$panzoom.on('panzoomend', function(e, panzoom, matrix, changed) {
 if (changed) {
  // deal with drags or touch moves
 } else {
   // deal with clicks or taps
 }
});

**Comment by bumbu** [comment]
Please post a [reproducible example](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues), otherwise it's hard to debug. 

Also take a look at similar issues, they may give you some insight: #148 and #156 

Also check [custom events demos](https://github.com/ariutta/svg-pan-zoom#demos) to see how you can disable default event handlers and implement your own.
