### ISSUE TITLE
Keep SVG content visible when zooming

### ISSUE THREAD

**Issue by ariutta** [ariutta/svg-pan-zoom#37]
Right now, it's possible to zoom into a blank area outside the bounding box of the SVG content. The view should never entirely leave the bounding box of the SVG content.

**Comment by bumbu** [comment]
I added ability to alter pan from beforePan callback.
Now you can return a object of type `{x: 10, y: 20}` and pan will be updated to these values.
In order to cancel pan you can pass oldPan.

> Currently you have minZoom and maxZoom variables, you have a beforePan method and a beforeZoom method. It occurs to me that you could replace all of these with a single "beforeChange" method that takes before and after values of x, y and zoom, and returns an object with the same set of values.

If this is still a _wanted_ feature then please open a new issue for this.
It may be an idea for version 4, but it has to be discussed.

Thanks

**Comment by hirschferkel** [comment]
> I added ability to alter pan from beforePan callback.
> Now you can return a object of type `{x: 10, y: 20}` and pan will be updated to these values.
> In order to cancel pan you can pass oldPan.

I made it work to limit the pan using the demo limit-pan.html but this seems to be different to the solution with a callback. Could you axplain how one could use the beforePan / oldPan method to limit the panning=

Best, hirschferkel

**Comment by hirschferkel** [comment]
@bumbu sorry I had only a sketchy look at it when I asked for help. Initially I used the method already... thank's for your help.
