### ISSUE TITLE
svg pan zoom and panning for multiple images not working

### ISSUE THREAD

**Issue by deeypak** [ariutta/svg-pan-zoom#84]
i want to override window object in svg-panzoom plugin,because i want to apply pan,zoom functionality to multiple image so i want to call panzoom function muliple times ,however svg-panzoom plugin works only with window object ,i want to call window.load object multiple times in my web page but it is not working ,so i want to override window object.

How to do it any body can answer?

**Comment by bumbu** [comment]
Please take a look at `demo/multi-instance`. Is that what you're looking for?

**Comment by rajeshchinnam** [comment]
Thanks for your reply.
in the multi-instance example we are using one div for each svg.and onload we are creating svgPanZoom object for each svg.so it was working for all the svgs
but what I am trying to do is in single div i want to update the svg object data dynamically by using java script as 
 document.getElementById("demo-tiger").data=svg filepath URL and trying to create svgPanZoom by using below function;
 function enable(filepath){
		 document.getElementById("demo-tiger").data=filepath;
		 
		svgPanZoom('#demo-tiger', {
          zoomEnabled: true,
          controlIconsEnabled: true
        });
}

when I try doing this I am getting this error
Uncaught TypeError: undefined is not a functionsvg-pan-zoom.js:488 
ShadowViewport.getCTMsvg-pan-zoom.js:400 
ShadowViewport.processCTMsvg-pan-zoom.js:330 
ShadowViewport.initsvg-pan-zoom.js:302 
ShadowViewportsvg-pan-zoom.js:622 
module.exportssvg-pan-zoom.js:677 
SvgPanZoom.initsvg-pan-zoom.js:633 
SvgPanZoomsvg-pan-zoom.js:1341 
svgPanZoomobject.html:12 
enableobject.html:25 
onclick

and on top this you mentioned 
// Don't use window.onLoad like this in production, because it can only listen to one function.
So Could you please help me how to fix this issue?

**Comment by bumbu** [comment]
It will not work by simply updating data attribute of SVG element like this `document.getElementById("demo-tiger").data=filepath`.

What you rather have to do if you want to update the contents of SVG is:

1. Destroy old svgpanzoom
* Destroy old SVG element
* Create new SVG element
* Initialize svgpanzoom on new element.

> Don't use window.onload like this in production, because it can only listen to one function.

You should be perfectly fine with `window.onload` if it is working for you. If you have jQuery then you can do 
```
jQuery(function(){
  //your code here
})
```

I put an example in `demo/dynamic-load` of how this can be done.
