### ISSUE TITLE
panzoom function event alert not working in chrome

### ISSUE THREAD

**Issue by deeypak** [ariutta/svg-pan-zoom#88]
Hi ,
in the below line of code ,the alert is not coming in chrome

function registerEvents() {
panZoom = svgPanZoom('#ev2d', {
	  zoomEnabled: true,
	  controlIconsEnabled: false,			
	  panEnabled: false,		
	  //fit: true,
	  beforeZoom: function(){		 
		alert("before zoom");
		}
		, onZoom: function(){
			alert("on zoom");
		}
		, beforePan: function(){			
		}
		, onPan: function(){			
		}
	});	      	 
  };
}

**Comment by bumbu** [comment]
Please provide a full example (you can host it online on a service like jsfiddle.net).
But I do believe that the problem is somewhere in your code (I just tested last build and it works file).
If it is not the library problem but a problem of your code then please post this question on stackoverflow (like stated [here](https://github.com/ariutta/svg-pan-zoom#support)) or any other help boards.
