### ISSUE TITLE
beforeZoom on return false doesn't halt

### ISSUE THREAD

**Issue by payzoff** [ariutta/svg-pan-zoom#99]
Hi, thank you for this very useful plugin. But I have a problem with zooming halt, posted to http://stackoverflow.com/questions/28889001/svgpanzoom-beforezoom-on-return-false-doesnt-halt, please check out

Thank you.

**Comment by bumbu** [comment]
_It works as expected. I replied to your question. I'll double the answer here in case anyone else stumbles on it:_
The problem is that when you zoom using mousescroll it is done relatively to the point of mouse pointer position. Thus you don't just scroll, you also pan.

In your example only prevents zooming but panning is still working when scrolling using mousescroll.

A solution would be to also cancel panning if it is right after zooming:
```
    beforeZoom: function(){
      isZooming = true;
      if(zoomed) {
        return false;
      } else {
        zoomed = true;
      }
    },
    beforePan: function(){
      if(isZooming) {
        isZooming = false;
        return false;
      }
    }
```
